### ISSUE TITLE
Implement LayernormGRU

### ISSUE THREAD

**Issue by ulf1** [kmedian/keras-layernorm-rnn#2]

**Comment by thegodone** [comment]
any update on this Issue ?

**Comment by ulf1** [comment]
@thegodone Sorry for the late reply. This repo went into the tensorflow/addons repo https://github.com/tensorflow/addons/blob/d126b4690e7858b85fdb3c9e9a61143c31e9fddb/tensorflow_addons/rnn/layer_norm_simple_rnn_cell.py (PR: https://github.com/tensorflow/addons/pull/841)

Right now TFA (tensorflow addons) has RNNs and LSTMs with layernorm. It's probably easier to adjust the LSTMCell code for GRU, e.g., https://github.com/tensorflow/addons/blob/d126b4690e7858b85fdb3c9e9a61143c31e9fddb/tensorflow_addons/rnn/layer_norm_lstm_cell.py

I will post an issue in TFA and link you there.

**Comment by ulf1** [comment]
@thegodone see https://github.com/tensorflow/addons/issues/2710
